language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
script: ant
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
install: /bin/true 
